[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on   = "<C-f>"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane min-preview"
desc = "Toggle preview pane"

[[mgr.prepend_keymap]]
on   = "q"
run  = "quit --no-cwd-file"
desc = "Quit without changing directory"

[[mgr.prepend_keymap]]
on   = "Q"
run  = "quit"
desc = "Quit and cd to current directory"

[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on   = ["g", "r"]
run  = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to git root"

[[mgr.prepend_keymap]]
on   = "<C-p>"
run  = 'shell -- qlmanage -p "$@" &>/dev/null'
desc = "Preview with Quick Look"

[[mgr.prepend_keymap]]
on   = "L"
run  = "plugin bypass"
desc = "Enter and skip single-child dirs"

[[mgr.prepend_keymap]]
on   = "H"
run  = "plugin bypass reverse"
desc = "Leave and skip single-child dirs"

[[mgr.prepend_keymap]]
on   = ["g", "d"]
run  = "cd ~/Downloads"
desc = "Go to Downloads"

[[mgr.prepend_keymap]]
on   = ["g", "D"]
run  = "cd ~/DEV"
desc = "Go to DEV"

[[mgr.prepend_keymap]]
on   = ["g", "."]
run  = "cd ~/.homesick/repos/dotfiles"
desc = "Go to dotfiles"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
