[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"

["Library/Fonts/sketchybar-app-font.ttf"]
    type = "file"
    url = "https://github.com/kvndrsslr/sketchybar-app-font/releases/latest/download/sketchybar-app-font.ttf"
    refreshPeriod = "720h"

[".config/sketchybar/lua/icon_map.lua"]
    type = "file"
    url = "https://github.com/kvndrsslr/sketchybar-app-font/releases/latest/download/icon_map.lua"
    refreshPeriod = "720h"
