#!/usr/bin/env zsh

#-----------------------------------------------------------
# @raisedadead's config files
# Copyright: Mrugesh Mohapatra <https://mrugesh.dev>
# License: ISC
#
# File name: home
# Wrapper for chezmoi + just dotfiles management
#-----------------------------------------------------------

case "${1:-}" in
  check|pull|push|status|verify|managed|init|apply|apply-public|apply-private|diff)
    just --justfile ~/.dotfiles/justfile --working-directory ~/.dotfiles "$@"
    ;;
  *)
    chezmoi "$@"
    ;;
esac
