gui:
  nerdFontsVersion: '3'
  border: rounded
  showRandomTip: false
  skipDiscardChangeWarning: true
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --features=catppuccin-mocha --paging=never
disableStartupPopups: true
quitOnTopLevelReturn: true
