gui:
  nerdFontsVersion: "3"
  border: rounded
  showRandomTip: false
  skipDiscardChangeWarning: true
  theme:
    activeBorderColor:
      - "#fab387"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#fab387"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --features=catppuccin-mocha --paging=never
disableStartupPopups: true
quitOnTopLevelReturn: true
