gui:
  nerdFontsVersion: '3'
  border: rounded
  showRandomTip: false
git:
  overrideGpg: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
disableStartupPopups: true
quitOnTopLevelReturn: true
