gui:
  nerdFontsVersion: '3'
  border: rounded
  showRandomTip: false
git:
  overrideGpg: false
  paging:
    colorArg: always
    useConfig: true
disableStartupPopups: true
quitOnTopLevelReturn: true
