#!/usr/bin/env lua
local home = os.getenv("HOME")
package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"
package.path = package.path .. ";" .. home .. "/.config/sketchybar/lua/?.lua"

sbar = require("sketchybar")
local colors = require("colors")

sbar.begin_config()
sbar.hotload(false)

sbar.bar({
	position = "bottom",
	height = 34,
	blur_radius = 20,
	color = colors.bar,
	padding_left = 10,
	padding_right = 10,
	corner_radius = 0,
	y_offset = 3,
	margin = 0,
	topmost = "window",
	sticky = "on",
	display = "all",
})

sbar.default({
	updates = "when_shown",
	icon = {
		font = { family = colors.icon_font, style = "Regular", size = 16.0 },
		color = colors.text,
		padding_left = 10,
		padding_right = 5,
	},
	label = {
		font = { family = colors.font, style = "Regular", size = 14.0 },
		color = colors.text,
		padding_left = 5,
		padding_right = 10,
	},
	background = { height = 22, corner_radius = 5 },
	padding_left = 4,
	padding_right = 4,
})

sbar.add("event", "aerospace_workspace_change")
sbar.add("event", "aerospace_mode_change")

require("items.spaces")
require("items.mode")
require("items.front_app")
require("items.widgets")

sbar.add("bracket", "left_island", {
	"space.1",
	"space.separator.2",
	"space.2",
	"space.separator.3",
	"space.3",
	"space.separator.4",
	"space.4",
	"space.separator.5",
	"space.5",
	"mode_indicator",
}, {
	background = {
		color = colors.island,
		corner_radius = 8,
		height = 28,
		border_width = 1,
		border_color = colors.island_border,
	},
})

sbar.end_config()
sbar.event_loop()
