#!/usr/bin/env lua
local home = os.getenv("HOME")
package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"
package.path = package.path .. ";" .. home .. "/.config/sketchybar/lua/?.lua"

sbar = require("sketchybar")
local colors = require("colors")

sbar.begin_config()
sbar.hotload(true)

sbar.bar({
	position = "bottom",
	height = 38,
	blur_radius = 30,
	color = colors.bar,
	padding_left = 8,
	padding_right = 8,
	corner_radius = 0,
	y_offset = 0,
	margin = 0,
	topmost = "window",
	sticky = "on",
	display = "all",
})

sbar.default({
	updates = "when_shown",
	icon = {
		font = { family = colors.icon_font, style = "Regular", size = 15.0 },
		color = colors.text,
		padding_left = 8,
		padding_right = 4,
	},
	label = {
		font = { family = colors.font, style = "Regular", size = 13.0 },
		color = colors.text,
		padding_left = 4,
		padding_right = 8,
	},
	background = { height = 24, corner_radius = 6 },
	padding_left = 3,
	padding_right = 3,
})

sbar.add("event", "aerospace_workspace_change")
sbar.add("event", "aerospace_mode_change")

require("items.spaces")
require("items.mode")
require("items.front_app")
require("items.widgets")

sbar.end_config()
sbar.event_loop()
