#-----------------------------------------------------------
#
# @raisedadead's config files
# Copyright: Mrugesh Mohapatra <https://mrugesh.dev>
# License: ISC
#
# File name: tmux.conf
#
#-----------------------------------------------------------

# Options
set -sg terminal-overrides ",*:RGB"
set -as terminal-features ",xterm-ghostty:hyperlinks"
set -as terminal-features ",xterm-ghostty:clipboard"
set -as terminal-features ",xterm-ghostty:extkeys"
set -g extended-keys on
set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g focus-events on
set -g history-limit 100000
set -g mouse on
set -g renumber-windows on
set -g set-clipboard on
set -gw mode-keys vi

# Prefix
set -g prefix C-Space
set -g prefix2 C-b
bind C-Space send-prefix
bind C-b send-prefix -2

# Modular configs
source-file ~/.config/tmux/keybinds.conf
source-file ~/.config/tmux/theme.conf

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_with_mouse off

set -g @plugin 'wfxr/tmux-fzf-url'
set -g @fzf-url-fzf-options '-p 53%,60% --border rounded --border-label=" URLs " --color=header:8,pointer:yellow,prompt:yellow,border:white,label:yellow'
set -g @fzf-url-history-limit '2000'
set -g @fzf-url-open 'open'

set -g @plugin 'tmux-plugins/tpm'
run '~/.config/tmux/plugins/tpm/tpm'
