# Monitoring
set -g monitor-activity on
set -g monitor-bell on
set -g visual-activity off
set -g visual-bell off
set -g activity-action other
set -g bell-action other
set -g allow-passthrough on

# Borders and messages
set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=white
set -g popup-border-style fg=white
set -g popup-style default
set -g message-style bg=magenta,fg=black
set -g message-command-style bg=cyan,fg=black
set -g mode-style bg=brightblack,fg=white
set -g display-time 1500

# Status bar
set -g status-style bg=default,fg=brightblack
set -g status-left ""
set -g status-right "#{S:#[fg=brightblack]■ ,#[fg=green]■ #{session_name} }"
set -g status-right-length 80
set -g window-status-format "#{?window_bell_flag,#[fg=brightyellow],#{?#{&&:#{@last_exit_code},#{!=:#{@last_exit_code},0}},#[fg=red],#{?window_activity_flag,#[fg=yellow],#[fg=brightblack]}}}●"
set -g window-status-current-format "#[fg=magenta]●"
set -gw window-status-activity-style none
set -gw window-status-bell-style none
