#-----------------------------------------------------------
#
# @raisedadead's config files
# Copyright: Mrugesh Mohapatra <https://mrugesh.dev>
# License: ISC
#
# File name: tmux.conf
#
#-----------------------------------------------------------

# Options
set -sg terminal-overrides ",*:RGB"
set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g focus-events on
set -g history-limit 100000
set -g mouse on
set -g renumber-windows on
set -g set-clipboard on
set -gw mode-keys vi

# Modular configs
source-file ~/.config/tmux/keybinds.conf
source-file ~/.config/tmux/theme.conf

# Plugins
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'fcsonline/tmux-thumbs'

# tmux-thumbs
set -g @thumbs-command 'echo -n {} | pbcopy'
set -g @thumbs-upcase-command 'tmux set-buffer -- {} && tmux paste-buffer && echo -n {} | pbcopy'
set -g @thumbs-reverse enabled
set -g @thumbs-unique enabled
set -g @thumbs-position off_left
set -g @thumbs-osc52 enabled
set -g @thumbs-bg-color black
set -g @thumbs-fg-color green
set -g @thumbs-hint-bg-color black
set -g @thumbs-hint-fg-color magenta
set -g @thumbs-select-fg-color cyan
set -g @thumbs-select-bg-color black
set -g @thumbs-multi-fg-color red
set -g @thumbs-multi-bg-color black

set -g @plugin 'tmux-plugins/tpm'
run '~/.config/tmux/plugins/tpm/tpm'
