onboarding = false
[ui]
show_agent_labels_on_pane_borders = true

agent_panel_sort = "spaces"
[experimental]
switch_ascii_input_source_in_prefix = true

[ui.toast]
delivery = "system"

[theme]
name = "catppuccin"
auto_switch = false

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"
