border: hidden
margin: 0
padding: 1
sep_width: 4
title: ""
prompt: "  "
placeholder: "..."
cursor_fg: "#1e1e2e"
cursor_bg: "#cba6f7"
filter_fg: "#f38ba8"
counter_fg: "#585b70"
placeholder_fg: "#585b70"
