import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

live_config_reload = true
working_directory = "~/DEV"

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.80
blur = true

[window.padding]
x = 8
y = 6

[window.dimensions]
lines = 45
columns = 175

[font]
size = 14.0

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF"
style = "Medium Italic"

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[[keyboard.bindings]] # split tmux window vertically
chars = "\u0002\""
key = "E"
mods = "Command"

[[keyboard.bindings]] # split tmux window horizontally
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]] # create new tmux window
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]] # kill current tmux pane
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]] # switch to next tmux window
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]] # switch to previous tmux window
chars = "\u0002p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]] # switch to previous tmux window
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]] # switch to next tmux window
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"
